In [38]:
from torch import nn
import torch

class Softmax(nn.Module):
    def __init__(self):
        super(Softmax, self).__init__()
    
    def forward(self, x):
        return x.exp() / x.exp().sum(-1).unsqueeze(-1)
    

class Softmax_stable(nn.Module):
    def __init__(self):
        super(Softmax_stable, self).__init__()

    def forward(self, x):
        exps = (x - x.max(-1)[0]).exp()
        return exps / exps.sum(-1).unsqueeze(-1)

In [31]:
data = torch.Tensor ([1 , 2 , 3])

softmax = Softmax()
output = softmax(data)
output

tensor([0.0900, 0.2447, 0.6652])

In [40]:
data = torch.Tensor ([1 , 2 , 3])
softmax_stable = Softmax_stable()
output = softmax_stable(data)
output

tensor([0.0900, 0.2447, 0.6652])

exercise 2

In [42]:
from abc import ABC, abstractmethod
class Person:
    def __init__(self, name, yob):
        self.name = name
        self.yob = yob
    
    @abstractmethod
    def describe(self):
        pass
    

class Student(Person):
    def __init__(self, name, yob, grade):
        super(Student, self).__init__(name, yob)
        self.grade = grade

    def describe(self):
        print(f"Student - Name: {self.name} - YOB: {self.yob} - Grade: {self.grade}")

class Teacher(Person):
    def __init__(self, name, yob, subject):
        super(Teacher, self).__init__(name, yob)
        self.subject = subject

    def describe(self):
        print(f"Teacher - Name: {self.name} - YOB: {self.yob} - Subject: {self.subject}")


class Doctor(Person):
    def __init__(self, name, yob, specialist):
        super(Doctor, self).__init__(name, yob)
        self.specialist = specialist

    def describe(self):
        print(f"Doctor - Name: {self.name} - YOB: {self.yob} - Specialist: {self.specialist}")



class Ward:
    def __init__(self, name):
        self.name = name
        self.__people_list = []
        
    def add_person(self, person):
        self.__people_list.append(person)

    def describe(self):
        print(f"Ward Name: {self.name}")
        for person in self.__people_list:
            person.describe()

    def count_doctor(self):
        count = 0
        for person in self.__people_list:
            if isinstance(person, Doctor):
                count += 1
        return count

    def sort_age(self):
        self.__people_list.sort(key=lambda x: x.yob)
        
    def compute_average(self):
        sum = 0
        for person in self.__people_list:
            sum += person.yob
        return int(sum / len(self.__people_list))

In [43]:

student1 = Student ( name =" studentA ", yob =2010 , grade ="7")
student1.describe ()

Student - Name:  studentA  - YOB: 2010 - Grade: 7


In [44]:
teacher1 = Teacher( name ="teacherA ", yob =1969 , subject ="Math")
teacher1.describe()

Teacher - Name: teacherA  - YOB: 1969 - Subject: Math


In [45]:
doctor1 = Doctor( name ="doctorA ", yob =1945 , specialist =" Endocrinologists ")
doctor1.describe ()

Doctor - Name: doctorA  - YOB: 1945 - Specialist:  Endocrinologists 


In [46]:

teacher2 = Teacher ( name ="teacherB ", yob =1995 , subject =" History ")
doctor2 = Doctor ( name ="doctorB ", yob =1975 , specialist =" Cardiologists ")
ward1 = Ward ( name ="Ward1 ")
ward1 . add_person ( student1 )
ward1 . add_person ( teacher1 )
ward1 . add_person ( teacher2 )
ward1 . add_person ( doctor1 )
ward1 . add_person ( doctor2 )
ward1 . describe ()

Ward Name: Ward1 
Student - Name:  studentA  - YOB: 2010 - Grade: 7
Teacher - Name: teacherA  - YOB: 1969 - Subject: Math
Teacher - Name: teacherB  - YOB: 1995 - Subject:  History 
Doctor - Name: doctorA  - YOB: 1945 - Specialist:  Endocrinologists 
Doctor - Name: doctorB  - YOB: 1975 - Specialist:  Cardiologists 


In [49]:
print(f"\n Number of doctors : {ward1.count_doctor()}")


 Number of doctors : 2


In [50]:
print("\n After sorting Age of Ward1 people ")
ward1 . sort_age ()
ward1 . describe ()


 After sorting Age of Ward1 people 
Ward Name: Ward1 
Doctor - Name: doctorA  - YOB: 1945 - Specialist:  Endocrinologists 
Teacher - Name: teacherA  - YOB: 1969 - Subject: Math
Doctor - Name: doctorB  - YOB: 1975 - Specialist:  Cardiologists 
Teacher - Name: teacherB  - YOB: 1995 - Subject:  History 
Student - Name:  studentA  - YOB: 2010 - Grade: 7


Exercise 3

In [52]:
class Stack:
    def __init__(self, capicity):
        self.__data = [] 
        self.__capicity = capicity

    def is_empty(self):
        return len(self.__data) == 0
    
    def is_full(self):
        return len(self.__data) == self.__capicity

    def push(self, value):
        if self.is_full():
            print("Stack is full")
            return
        self.__data.append(value)

    def pop(self):
        if self.is_empty():
            print("Stack is empty")
            return
        popped_value = self.__data[-1]
        self.__data.pop()
        return popped_value
    
    def top(self):
        if self.is_empty():
            print("Stack is empty")
            return
        return self.__data[-1]
        

In [58]:
stack1 = Stack(capicity=5)
print(stack1.is_empty())

True


In [59]:
print(stack1.is_full())

False


In [60]:
stack1.push(1)
stack1.push(2)


In [61]:
print(stack1.top())

2


In [62]:
print(stack1.pop())

2


In [63]:
print(stack1.top())

1


In [64]:
print(stack1.pop())

1


In [65]:
print(stack1.pop())

Stack is empty
None


In [66]:
print(stack1.is_empty())

True


Excercise 4

In [67]:
class Queue:
    def __init__(self, capicity):
        self.__data = [] 
        self.__capicity = capicity

    def is_empty(self):
        return len(self.__data) == 0
    
    def is_full(self):
        return len(self.__data) == self.__capicity

    def enqueue(self, value):
        if self.is_full():
            print("Queue is full")
            return
        self.__data.append(value)

    def dequeue(self):
        if self.is_empty():
            print("Queue is empty")
            return
        dequeued_value = self.__data[0]
        self.__data.pop(0)
        return dequeued_value
    
    def front(self):
        if self.is_empty():
            print("Queue is empty")
            return
        return self.__data[0]

In [68]:
queue1 = Queue(capicity=5)
print(queue1.is_empty())

True


In [69]:
queue1.enqueue(1)
queue1.enqueue(2)
queue1.enqueue(3)

In [70]:
queue1.is_full()

False

In [71]:
queue1.front()

1

In [72]:
queue1.dequeue()

1

In [73]:
queue1.front()

2

In [74]:
queue1.dequeue()

2

In [77]:
queue1.dequeue()

3

In [78]:
queue1.is_empty()

True

Multi choices

In [84]:
import torch
import torch . nn as nn

class SoftmaxStable ( nn . Module ):
    def __init__ ( self ) :
        super () . __init__ ()

    def forward ( self , x ) :
        x_max = torch .max(x , dim =0 , keepdims = True )
        x_exp = torch . exp ( x - x_max . values )
        partition = x_exp .sum (0 , keepdims = True )
        return x_exp / partition

data = torch . Tensor ([1 , 2 , 3])
softmax_stable = SoftmaxStable ()
output = softmax_stable ( data )
assert round ( output [ -1]. item () , 2) == 0.67
output

tensor([0.0900, 0.2447, 0.6652])